Fix isAtPosition and rotateN
Spartronics4915/2020-InfiniteRecharge pull request #129
Opened 2020-02-17 03:13 UTC by j-james

2020-02-17 04:13 UTC, j-james commented
@thehappycamden how is [this function](https://github.com/Spartronics4915/2020-InfiniteRecharge/blob/master/src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java#L160) supposed to work?

2020-02-17 17:54 UTC, pietroglyph requested changes

2020-02-17 17:54 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/commands/IndexerCommands.java
> +            super(indexer::getIntakeEmpty);
Why would we wait for the intake to be empty to stop the intake?

2020-02-17 17:54 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
>          return !mIntakeProxSensor.get();
This change doesn’t make any sense.

2020-02-17 17:54 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +        return (positionMod90 >= (90 - Constants.Indexer.Spinner.kPositionTolerance)
This is fixed in Camden’s branch.

2020-02-17 17:54 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +            double deltaPosition = 0.25 * N; // Convert N to rotations
This is fixed in Camden’s branch.

2020-02-18 18:50 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +        return !mOpticalProxSensor.get();
Fixed in Camden's PR

2020-02-24 22:54 UTC, pietroglyph requested changes

2020-02-24 22:54 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +            mTargetPosition = deltaPosition + mIndexerMotor.getEncoder().getPosition();
This change is not desirable. We want to keep track of target positions. If we used this PR then the target position would drift.

2020-02-25 01:41 UTC, closed without merging