Stops the wheel if the arm is down
Spartronics4915/2020-InfiniteRecharge pull request #136
Opened 2020-02-17 20:08 UTC by TheHarmonicRealm

2020-02-18 18:49 UTC, omentic requested changes

2020-02-18 18:49 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/commands/PanelRotatorCommands.java
> +import com.fasterxml.jackson.databind.deser.std.MapEntryDeserializer;
???

2020-02-18 18:49 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/commands/PanelRotatorCommands.java
> +    public class Raise extends CommandBase
You can consolidate this all to a FunctionalCommand

2020-02-18 18:49 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/commands/PanelRotatorCommands.java
> +    /*
Add back in documentation

```
/**
 * This Raise {@link FunctionalCommand} calls {@link PanelRotator}.raise
 * repeatedly, until the upper optical flag is broken, at which point the
 * motor will stop.
 * <p>
 * The motor will also stop raising if interrupted by another Command.
 */
```

2020-02-18 18:49 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/PanelRotator.java
> +    private final ColorSensorV3 mColorSensor;
Move where these hardware are

2020-02-18 18:49 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/PanelRotator.java
> +    /**
Proximity sensor has been cut.

2020-02-18 18:49 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/PanelRotator.java
> +        mProximitySensor = new DigitalInput(Constants.PanelRotator.kProximitySensorId);
Proximity sensor has been cut

2020-02-18 18:49 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/PanelRotator.java
> +    public void getDistance()
Ooh, maybe using this would be more reliable than `getColorConfidence()`.

2020-02-18 18:49 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/PanelRotator.java
> +    public void getDistance()
We should test that if possible.

2020-02-18 18:49 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/PanelRotator.java
> +        this.dashboardPutString("Color sensor 18 Bit", RGB);
What's the idea behind this change?

2020-02-18 23:48 UTC, TheHarmonicRealm commented on src/main/java/com/spartronics4915/frc2020/commands/PanelRotatorCommands.java
> +import com.fasterxml.jackson.databind.deser.std.MapEntryDeserializer;
I have no idea where this came from

2020-02-28 04:09 UTC, j-james commented
There's some really weird issues with this PR, GitHub / git seems to think changes that haven't been made have been (mostly around subsystem pass-through). @TheHarmonicRealm I'm going to `git cherry-pick` your commits into `master`...

2020-02-28 04:09 UTC, closed without merging