Indexer Subsystem stubs
Spartronics4915/2020-InfiniteRecharge pull request #25
Opened 2020-01-18 01:41 UTC by thehappycamden

Wrote stubs for indexer API

2020-01-18 09:27 UTC, omentic requested changes

2020-01-18 09:27 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    public int mSpinnerId = -1;
These should be in Constants.java as `public static final int kSubsystemDescriptorID`.

2020-01-18 09:27 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    {
Bracket styles

2020-01-18 09:27 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    public int rotateFull() {}
Extra closing bracket

2020-01-18 09:27 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    public int rotateCounterClockwiseFull() {
Why do you return `int`s for these?

2020-01-18 09:39 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    public int mSpinnerId = -1;
Remember to add all devices IDs to the [2020 control map](https://docs.google.com/spreadsheets/d/14O3Dj1Bl6tqiHFrCJ7wyVRDOqS5EZ11p4q9j2rYS-3Q/edit#gid=0).

2020-01-18 22:26 UTC, thehappycamden commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    public int rotateCounterClockwiseFull() {
number of quarter rotations

2020-01-19 07:52 UTC, omentic requested changes

2020-01-19 07:52 UTC, j-james commented on src/main/java/com/spartronics4915/frc2020/Constants.java
> +    public static final int kIndexerSpinnerId = -1;
Our new convention is to have all subsystem variables be in their own subclass, so it'll look like this (and `Indexer` is stricken from the name): 

```
public final class Constants {
    public static final class Indexer { 
        public static final int kSpinnerId = -1;
         ... other variables
    }
    // ... other subclasses
}
```

2020-01-23 04:10 UTC, omentic approved these changes

2020-01-23 04:11 UTC, merged