Added setPosition functions to SpartronicsMax and SpartronicsSRX
Spartronics4915/2020-InfiniteRecharge pull request #58
Opened 2020-01-25 04:05 UTC by thehappycamden

2020-01-26 19:06 UTC, pietroglyph requested changes

2020-01-26 19:06 UTC, pietroglyph commented on src/main/java/com/spartronics4915/lib/hardware/motors/SpartronicsEncoder.java
> +            Logger.error("Couldn't set the phase of a disconnected encoder");
This logger message doesn't make sense.

2020-01-30 00:25 UTC, thehappycamden commented
Also added Indexer code, pull request hadn't been updated yet

2020-01-30 01:58 UTC, pietroglyph requested changes
Just a couple of naming nitpicks.

2020-01-30 01:58 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
>      // setIntake functionality should be implemented in a command.
Remove this

2020-01-30 01:58 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    public void returnSpin()
Change to `returnToHome`?

2020-01-30 01:58 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    public void endSpinner()
Change to `toNearestQuarterRotation`?

2020-01-30 01:58 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    public boolean getLaunching()
Change to `isLaunching`?

2020-01-30 01:58 UTC, pietroglyph commented on src/main/java/com/spartronics4915/frc2020/subsystems/Indexer.java
> +    public void load()
Change to `loadBalls`?

2020-01-30 02:52 UTC, merged

2020-01-30 02:57 UTC, thehappycamden commented
yay